// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveModules() {
  return window['go']['main']['App']['GetActiveModules']();
}

export function GetItems(arg1, arg2) {
  return window['go']['main']['App']['GetItems'](arg1, arg2);
}

export function SaveItem(arg1) {
  return window['go']['main']['App']['SaveItem'](arg1);
}
