// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteItem(arg1:string):Promise<void>;

export function ExportBackup():Promise<string>;

export function GetActiveModules():Promise<Array<main.ModuleSchema>>;

export function GetItems(arg1:string,arg2:string,arg3:string):Promise<Array<main.Item>>;

export function LoadModuleFile(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function ProcessImage(arg1:string):Promise<main.ProcessImageResult>;

export function SaveCustomModule(arg1:string):Promise<main.ModuleSchema>;

export function SaveItem(arg1:main.Item):Promise<main.Item>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectImageFile():Promise<string>;
