// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GetActiveModules() {
  return window['go']['main']['App']['GetActiveModules']();
}

export function GetItems(arg1, arg2) {
  return window['go']['main']['App']['GetItems'](arg1, arg2);
}

export function LoadModuleFile(arg1) {
  return window['go']['main']['App']['LoadModuleFile'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function ProcessImage(arg1) {
  return window['go']['main']['App']['ProcessImage'](arg1);
}

export function SaveCustomModule(arg1) {
  return window['go']['main']['App']['SaveCustomModule'](arg1);
}

export function SaveItem(arg1) {
  return window['go']['main']['App']['SaveItem'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}
