// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetActiveModules():Promise<Array<main.ModuleSchema>>;

export function GetItems(arg1:string,arg2:string):Promise<Array<main.Item>>;

export function SaveItem(arg1:main.Item):Promise<main.Item>;
